# Generated by Django 3.2.4 on 2021-06-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0003_alter_cart_meal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='meal',
            field=models.ManyToManyField(to='deliver.Meal'),
        ),
    ]
