# Generated by Django 3.2.4 on 2021-06-10 17:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_auto_20210609_1544'),
        ('deliver', '0004_alter_cart_meal'),
    ]

    operations = [
        migrations.AddField(
            model_name='meal',
            name='manager',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Meal', to='account.manager'),
        ),
    ]
