# Generated by Django 3.2.4 on 2021-06-10 18:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0005_meal_manager'),
    ]

    operations = [
        migrations.RenameField(
            model_name='meal',
            old_name='manager',
            new_name='owner',
        ),
    ]
