# Generated by Django 3.2.4 on 2021-06-11 12:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0006_rename_manager_meal_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='owner',
        ),
    ]
