# Generated by Django 3.2.4 on 2021-06-12 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0013_alter_cart_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
