# Generated by Django 3.2.4 on 2021-06-13 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0015_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='photo',
            field=models.ImageField(blank=True, upload_to='photos/'),
        ),
    ]
