# Generated by Django 3.2.4 on 2021-06-13 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0016_alter_restaurant_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='meal',
            name='ingredients',
            field=models.TextField(blank=True),
        ),
    ]
