# Generated by Django 3.2.4 on 2021-06-15 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0017_alter_meal_ingredients'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='price',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
