# Generated by Django 3.2.4 on 2021-06-15 13:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0018_alter_cart_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='restaurant',
        ),
        migrations.AddField(
            model_name='cart',
            name='restaurant',
            field=models.ManyToManyField(null=True, to='deliver.Restaurant'),
        ),
    ]
