# Generated by Django 3.2.4 on 2021-06-15 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0024_auto_20210615_2106'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='restaurant',
            name='manager',
        ),
    ]
