# Generated by Django 3.2.4 on 2021-06-15 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0026_restaurant_manager'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='restaurant',
            field=models.ManyToManyField(blank=True, to='deliver.Restaurant'),
        ),
    ]
