# Generated by Django 3.2.4 on 2021-06-18 13:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliver', '0027_alter_order_restaurant'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='meal',
            name='order',
        ),
        migrations.AddField(
            model_name='meal',
            name='order',
            field=models.ManyToManyField(blank=True, null=True, to='deliver.Order'),
        ),
    ]
